# Generated by Django 6.0 on 2026-02-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("listing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="listings.listing")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["user", "status"], name="bookings_bo_user_id_344f2d_idx"), models.Index(fields=["listing", "start_date", "end_date"], name="bookings_bo_listing_0fd8af_idx")],
                "constraints": [models.CheckConstraint(condition=models.Q(("end_date__gt", models.F("start_date"))), name="booking_end_date_after_start_date")],
            },
        ),
    ]
